### ISSUE TITLE
Arranging projects in proper order

### ISSUE THREAD

**Issue by Mayank-Garg7** [theyogesh10/JavaScript-Projects#1]
## Arrange Projects in Order

To display your projects in the correct serial order on GitHub, rename them with leading zeros, e.g., **`project-01`**, **`project-02`**, ..., **`project-16`**. This resolves the issue where **`project-10`** appears before **`project-2`** due to alphabetical sorting.

### Steps:
1. **Rename Directories**:
   - Rename locally:
     - **`project-1`** → **`project-01`**
     - **`project-2`** → **`project-02`**
     - ... up to **`project-16`**.

2. **Use Git Commands**:
   ```bash
   git mv project-1 project-01
   git mv project-2 project-02
   ```
   Repeat for all directories.

3. **Commit and Push**:
   ```bash
   git commit -m "Rename directories for proper order"
   git push
   ```

### Result:
Your projects will appear as:
```
project-01
project-02
...
project-16
```

**Comment by theyogesh10** [comment]
Thank you @Mayank-Garg7 for your solution to the GitHub project order issue. Renaming the directories with leading zeros worked perfectly, and everything is now in the correct order. I really appreciate your help!
